# -*- coding: utf-8 -*-
"""basic correlation project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19mWOtdIBCIqRCzw8c1n6FyEMC5GPu_mX
"""

# Commented out IPython magic to ensure Python compatibility.
# Purpose of code: find correlation between budget and revenue/gross
#(trying to see if the more the budget we had for the film the more the revenue generated and if ratings affect gross as well)
import pandas as pd
import seaborn as sns
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
from matplotlib.pyplot import figure

# %matplotlib inline
matplotlib.rcParams['figure.figsize'] = (12,8) # adjusts the configuration of the plots we will create


#read in the data

df = pd.read_csv("/content/movies.csv")

df.dtypes

# looking for missing data
for col in df.columns:
    pct_missing = np.mean(df[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))

# Drop rows where the 'budget' column has missing values
df.dropna(subset=['budget', 'gross'], inplace=True)

df['budget'] = df['budget'].astype('int64')
df['gross'] = df['gross'].astype('int64')
df['votes'] = df['votes'].astype('int64')

df.sort_values(by=['gross'], inplace=False, ascending=False)

pd.set_option('display.max_rows', None)

# Drop duplicates
df.drop_duplicates()

# checking if the Budget have high correlation
# check if company(bigger company names) have high correlation

#scatter plot with budget vs gross
plt.scatter(x=df['budget'], y=df['gross'])
plt.title('Budget vs Gross Earnings')
plt.xlabel('Gross Earnings')
plt.ylabel('Budget for Film')
plt.show()

#using seaburn plot budget vs gross
sns.regplot(x='budget', y='gross', data=df, scatter_kws={'color':'red'}, line_kws={'color':'blue'})

df.corr(method="pearson", numeric_only=True)

#High correlation between budget and gross as seen in the table above

correlation_matrix = df.corr(method="pearson", numeric_only=True)
sns.heatmap(correlation_matrix, annot = True)
plt.title('Correlation Matrix for numeric features')
plt.xlabel('Movie Features')
plt.ylabel('Movie Features')
plt.show()

# the company column is in words, i want to give it numerical rep. so i can use it to compare it to gross

df_numerized = df
for col_name in df_numerized.columns:
    if(df_numerized[col_name].dtype == 'object'):
        df_numerized[col_name]= df_numerized[col_name].astype('category')
        df_numerized[col_name]= df_numerized[col_name].cat.codes

df_numerized

df_numerized.sort_values(by=['gross'], inplace=False, ascending=False)

correlation_matrix = df_numerized.corr(method="pearson", numeric_only=True)
sns.heatmap(correlation_matrix, annot = True)
plt.title('Correlation Matrix for numeric features')
plt.xlabel('Movie Features')
plt.ylabel('Movie Features')
plt.show()

# so from the heat map we can see that company and gross didnt have a strong correlation
# intrestingly we can also see that gross and votes have a fairly good correlation

high_corr = sorted_pairs[sorted_pairs > 0.5]
high_corr

# Gross and Budget have the highest correlation followed by votes and Gross