# -*- coding: utf-8 -*-
"""canada per ca[ita income analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YvC9o9g_nDPN5WSEAFzHKO6o1MURnaU-
"""

#Import Librarries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.linear_model import LinearRegression

df = pd.read_csv('/content/sample_data/canada_per_capita_income.csv')

# Commented out IPython magic to ensure Python compatibility.
#Visualizing the data
# %matplotlib inline
plt.xlabel('year')
plt.ylabel('per capita income (US$)')
plt.scatter(df.year,df['per capita income (US$)'],color='red',marker='+')

#Training the Linear Regression Model
reg = linear_model.LinearRegression()
reg.fit(df[['year']],df['per capita income (US$)'])

reg.predict([[2020]])

# Lets figur out how this works
# A basic linera model uses basic linear equation we learnt from maths in Sec.school
# y=mx + c where m= slope and c= intercept
# so if i want to test if it is correct i just find the coefficient and intercpet
# then put it in the exquation to find y again

reg.coef_

reg.intercept_

# y=mx+c
828.46507522*2020 + -1632210.7578554575

# Commented out IPython magic to ensure Python compatibility.
#Visualizing the data
# %matplotlib inline
plt.xlabel('year')
plt.ylabel('per capita income (US$)')
plt.scatter(df.year,df['per capita income (US$)'],color='red',marker='+')
plt.plot(df.year,reg.predict(df[['year']]),color='blue')

