# -*- coding: utf-8 -*-
"""Time Series Analysis of Daily Female Births in California.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uSv1o3zUBgqCVMAxRWJbuuNAeRgZrLNw
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.stattools import adfuller, acf, pacf
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.graphics.gofplots import qqplot
from scipy.stats import probplot

data = pd.read_csv('/content/CA female births_2coWUjq.csv')

data

data.head()

data.dtypes

data.describe

data['date'] = pd.to_datetime(data['date'])

data

data['date'] = pd.to_datetime(data['date'], format="%m/%d/%Y")

data.set_index('date', inplace=True)

data = data['births']

data.plot(title='Daily Female Births (California, 1959)', figsize=(10,4))
plt.show()

from statsmodels.tsa.stattools import adfuller
adf_result = adfuller(data)
print(f'ADF Statistic: {adf_result[0]}')
print(f'p-value: {adf_result[1]}')

plot_acf(data, lags=30)
plot_pacf(data, lags=30)
plt.show()

from statsmodels.tsa.arima.model import ARIMA
model = ARIMA(data, order=(2, 0, 1))  # ARMA(2,1)
result = model.fit()
print(result.summary())

residuals = result.resid

fig, axs = plt.subplots(2, 2, figsize=(12, 8))

axs[0, 0].plot(residuals)
axs[0, 0].set_title("Residual Sequence Plot")
axs[0, 0].set_xlabel("Time")
axs[0, 0].set_ylabel("Residuals")

sns.histplot(residuals, kde=True, ax=axs[0, 1])
axs[0, 1].set_title("Histogram of Residuals")

#QQplot
qqplot(residuals, line='s', ax=axs[1, 0])
axs[1, 0].set_title("Q-Q Plot")

# ACF Plot of residuals
plot_acf(residuals, lags=30, ax=axs[1, 1])
axs[1, 1].set_title("ACF of Residuals")
plt.tight_layout()
plt.show()

# Q-Q plot
plt.figure(figsize=(6, 4))
qqplot(residuals, line='s')
plt.title("Q-Q Plot of Residuals")
plt.show()

# ACF plot of residuals
plt.figure(figsize=(6, 4))
plot_acf(residuals, lags=30)
plt.title("ACF of Residuals")
plt.show()

# Sequence plot
plt.figure(figsize=(10, 4))
plt.plot(residuals)
plt.title("Residual Sequence Plot")
plt.xlabel("Time")
plt.ylabel("Residuals")
plt.show()

# Histogram with KDE
plt.figure(figsize=(6, 4))
sns.histplot(residuals, kde=True)
plt.title("Histogram of Residuals")
plt.show()

forecast = result.get_forecast(steps=30)
forecast_mean = forecast.predicted_mean
forecast_ci = forecast.conf_int()

# Plot original + forecast
plt.figure(figsize=(12, 5))
plt.plot(data, label='Observed')  # historical data
plt.plot(forecast_mean, label='Forecast', color='orange')  # predicted values
plt.fill_between(
    forecast_ci.index,
    forecast_ci.iloc[:, 0],  # lower bound
    forecast_ci.iloc[:, 1],  # upper bound
    color='pink', alpha=0.3, label='Confidence Interval'
)

plt.title("Daily Female Births Forecast (Next 30 Days)")
plt.xlabel("Date")
plt.ylabel("Births")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

